# Generated by Django 3.2.7 on 2021-10-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pix',
            field=models.ImageField(blank=True, default='../img/avartar.png', null=True, upload_to='img/profiles/'),
        ),
    ]
