# Generated by Django 3.2.7 on 2021-09-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_main_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='main_photo',
        ),
    ]
