# Generated by Django 3.2.7 on 2021-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_photo',
            field=models.ImageField(blank=True, default='thumbnail.png', null=True, upload_to=''),
        ),
    ]
